CREATE TABLE [dbo].[DimCustomer] (

	[CustomerKey] int NULL, 
	[Active] bit NULL, 
	[CompanyName] varchar(200) NULL, 
	[DisplayName] varchar(200) NULL, 
	[FamilyName] varchar(200) NULL, 
	[FullyQualifiedName] varchar(200) NULL, 
	[GivenName] varchar(200) NULL, 
	[Id] int NULL, 
	[MiddleName] varchar(200) NULL, 
	[PreferredDeliveryMethod] varchar(200) NULL, 
	[PrintOnCheckName] varchar(200) NULL, 
	[Taxable] bit NULL, 
	[BillAddr_City] varchar(200) NULL, 
	[BillAddr_Country] varchar(200) NULL, 
	[BillAddr_CountrySubDivisionCode] varchar(200) NULL, 
	[BillAddr_Id] int NULL, 
	[BillAddr_Lat] float NULL, 
	[BillAddr_Line1] varchar(200) NULL, 
	[BillAddr_Long] float NULL, 
	[BillAddr_PostalCode] int NULL, 
	[Mobile_FreeFormNumber] varchar(200) NULL, 
	[PrimaryEmailAddr_Address] varchar(200) NULL, 
	[PrimaryPhone_FreeFormNumber] varchar(200) NULL, 
	[ShipAddr_City] varchar(200) NULL, 
	[ShipAddr_Country] varchar(200) NULL, 
	[ShipAddr_CountrySubDivisionCode] varchar(200) NULL, 
	[ShipAddr_Id] int NULL, 
	[ShipAddr_Lat] float NULL, 
	[ShipAddr_Line1] varchar(200) NULL, 
	[ShipAddr_Long] float NULL, 
	[ShipAddr_PostalCode] int NULL, 
	[WebAddr_URI] varchar(200) NULL, 
	[InsertDate] datetime2(3) NULL, 
	[UpdateDate] datetime2(3) NULL
);