CREATE TABLE [dbo].[DimVendor] (

	[VendorKey] int NULL, 
	[Active] bit NULL, 
	[CompanyName] varchar(80) NULL, 
	[DisplayName] varchar(80) NULL, 
	[FamilyName] varchar(80) NULL, 
	[GivenName] varchar(80) NULL, 
	[Id] int NULL, 
	[MiddleName] varchar(80) NULL, 
	[PrintOnCheckName] varchar(80) NULL, 
	[Suffix] varchar(20) NULL, 
	[Title] varchar(20) NULL, 
	[BillRate] int NULL, 
	[BillAddr_City] varchar(80) NULL, 
	[BillAddr_Country] varchar(80) NULL, 
	[BillAddr_CountrySubDivisionCode] varchar(80) NULL, 
	[BillAddr_Id] int NULL, 
	[BillAddr_Lat] float NULL, 
	[BillAddr_Line1] varchar(80) NULL, 
	[BillAddr_Long] float NULL, 
	[BillAddr_PostalCode] int NULL, 
	[PrimaryEmailAddr_Address] varchar(80) NULL, 
	[PrimaryPhone_FreeFormNumber] varchar(80) NULL, 
	[TermRef_name] varchar(80) NULL, 
	[TermRef_value] int NULL, 
	[WebAddr_URI] varchar(80) NULL, 
	[InsertDate] datetime2(3) NULL, 
	[UpdateDate] datetime2(3) NULL
);